### ISSUE TITLE
Empty error-div is included already on load and if there is no error.

### ISSUE THREAD

**Issue by animaux** [tobimori/kirby-dreamform#49]
The following code is always included in the form. Apart from semantic/redundancy reasons this creates an empty box when styling the error message with a background and padding:

`<div class="error" data-error=""></div>`

<img width="42" alt="Skjermbilde 2024-05-03 kl  11 13 30" src="https://github.com/tobimori/kirby-dreamform/assets/446874/f8bfd7a5-c584-4734-b07a-38e55b8c1631">

**Comment by tobimori** [comment]
This is expected behaviour, so it's easier to show errors when using API submission mode. 

If you want to customize it, you can override the error snippet in `site/snippets/dreamform/fields/partials/error.php` and `site/snippets/dreamform/form.php` wrap them both in an `if` statement.

However, my recommended solution would be to hide the div with `.error:empty { display: none; }`.

**Comment by animaux** [comment]
Hmn ok. Already did that as a quick fix. Support is [quite good](https://caniuse.com/mdn-css_selectors_empty) nowadays.
